### ISSUE TITLE
Negative array indexing bug

### ISSUE THREAD

**Issue by JimiHFord** [artfwo/andes#16]
Unfortunately I haven't figured out how to "immediately" reproduce this bug, but I believe the `Noise::gen`  method has a math bug that is causing negative array indexing in `Noise::gen1`.

```c++
// line of code causing array index out of bounds
// z1 is a very large negative number (e.g. -187420688)
g1 = gradients[z1];
```

If you turn `warping`, `octaves` and `persistence` all the way up, and alternate between modulating `torsion` with the mouse and spam clicking on the randomize button, you'll be able to (eventually) reproduce it.

What I think could be happening is that in the loop that iterates through the octaves, there is some sort of compound "rounding" (e.g. casting float to int) issue that gets worse each time through the loop because the negative array indexing only happens after a few successful iterations through the octave loop.

Let me know if you have trouble reproducing this. I want to figure this out but... it's almost 4am 😴

**Comment by artfwo** [comment]
Hey @JimiHFord! Looking into this, thanks for reporting!

**Comment by JimiHFord** [comment]
Awesome yeah, my pleasure! This project is helping me sooo much, thanks for your work!

**Comment by JimiHFord** [comment]
I just realized I should mention that I was holding down a key on my midi controller while alternating between modulating torsion and spamming the randomize button. I don't know the ins-and-outs of Juce yet, but I _think_ the `gen` code is only getting run while the synthesizer is producing sound - but I could be wrong about this.

**Comment by artfwo** [comment]
The bug basically happens, because the waveform has amplitude > 2 with high persistence so, when warped, the x value will be outside of the usual range (0..2)
