### ISSUE TITLE
pitchbend support

### ISSUE THREAD

**Issue by rghvdberg** [artfwo/andes#8]
please add pitchbend support :-)

**Comment by artfwo** [comment]
on it :)

**Comment by rghvdberg** [comment]
I wanna make a song using only this synth :-)
When you gimme pitchbend I can make just about any sound ..

**Comment by artfwo** [comment]
@rghvdberg, need a fresh build with pitch wheel? :)

**Comment by rghvdberg** [comment]
yup !

**Comment by artfwo** [comment]
@rghvdberg for 64-bit linux try this [preliminary build](https://www.dropbox.com/s/biqpgsydhfm612c/Andes1-0.1-linux-x86_64-pitchwheel.tar.gz?dl=0).

**Comment by artfwo** [comment]
And good luck with that track! Send me a link when you're done :)

**Comment by rghvdberg** [comment]
works :+1: :tada: 
but .. could I get more range, like 24 semitones ????

please ?

**Comment by artfwo** [comment]
Sure, try [this build](https://www.dropbox.com/s/biqpgsydhfm612c/Andes1-0.1-linux-x86_64-pitchwheel.tar.gz?dl=0).

But I'm gonna leave this change out of the release version until I implement modulation so we'll have configurable range :)

**Comment by rghvdberg** [comment]
Yes, that would be necessary. Set pitchbend depth.
Very)ery interesting synth.

FYI, when you think it's ready I'm gonna propose this synth for the KVR One
Synth Challenge.
https://sites.google.com/site/kvrosc/

We have a slack channel (https://one-synth-challenge.herokuapp.com/)  and a
matrix room (which is linked to the slack channel btw).

One Synth Challenge

WORLD READABLE

GUESTS CAN JOIN
make a song wih only one synth plugin
#osc:matrix.org

Some folks over there already compiled it on OSX :)
